spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:
          routes:

            # -------------------------
            # AUTH SERVICE ROUTE
            # -------------------------
            - id: auth-service-route
              uri: http://localhost:4002
              predicates:
                - Path=/api/auth/**

            # -------------------------
            # EQUITY TRACKER SERVICE ROUTE
            # -------------------------
            - id: equity-tracker-service-route
              uri: http://localhost:4001
              predicates:
                - Path=/api/stocks/**

            # -------------------------
            # PORTFOLIO SERVICE ROUTE
            # -------------------------
            - id: portfolio-service-route
              uri: http://localhost:4000
              predicates:
                - Path=/api/portfolio/**

server:
  port: 4003
